name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Installing dependencies
      run: sudo apt-get install zip unzip wget
    - name: Get c8y
      run: wget -O /etc/apk/keys/reuben.d.miller\@gmail.com-61e3680b.rsa.pub https://reubenmiller.github.io/go-c8y-cli-repo/alpine/PUBLIC.KEY
    - name: Install c8y
      run: sh -c "echo 'https://reubenmiller.github.io/go-c8y-cli-repo/alpine/stable/main'" >> /etc/apk/repositories   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-microservice-name
    - name: Saving Container
      run: docker save my-microservice-name > "image.tar"
    - name: Zipping the container with the cumulocity manifest
      run: zip my-microservice-name cumulocity.json image.tar
    - name: Setting/Session create
      run: c8y sessions create --type dev --host "https://${C8Y_HOST}" --username "${C8Y_USER}" --password "$C8Y_PW"
    - name: Set Session  
      run: eval $(c8y sessions set --shell bash --session ~/.cumulocity//${C8Y_HOST}-${C8Y_USER}.json)
    - name: Uploading Microservice
      run: c8y microservices create --file my-microservice-name.zip
